### PR TITLE
fixed the error

### PR DESCRIPTION
**Pull request by isaacsanders**

### CODE REVIEW

**Comment by wakproductions** [comment]
Running the benchmarks on it now... will have it merged in a jiffy

**Comment by isaacsanders** [comment]
Some mistakes, a new PR coming in soon

**Comment by isaacsanders** [comment]
kyle still has it

**Comment by isaacsanders** [comment]
```
 $ ruby run/run.rb

  [Isaac, Kyle, Kyle (monkeypatch), Mack, Miles, Original, Winston]

  +--------------------+-----------+
  | tach               | total     |
  +--------------------+-----------+
  | Kyle (monkeypatch) | 26.323733 |
  +--------------------+-----------+
  | Kyle               | 26.971578 |
  +--------------------+-----------+
  | Isaac              | 27.080527 |
  +--------------------+-----------+
  | Mack               | 28.597245 |
  +--------------------+-----------+
  | Miles              | 37.370611 |
  +--------------------+-----------+
  | Original           | 37.856693 |
  +--------------------+-----------+
  | Winston            | 38.617371 |
  +--------------------+-----------+
```

**Pull request closed without merging**
